import { GameLevel, Badge } from "./types";

export const AVATARS = [
  { id: "petualang1", name: "Alif", desc: "Siswa Petualang yang Cerdik", emoji: "🎒" },
  { id: "petualang2", name: "Bening", desc: "Siswa Pencari Logika", emoji: "🧭" },
  { id: "petualang3", name: "Candra", desc: "Ahli Peta & Koordinat", emoji: "🗺️" },
  { id: "petualang4", name: "Dina", desc: "Ahli Angka & Data", emoji: "📊" },
];

export const BADGES: Badge[] = [
  { id: "pioneer", name: "Penjelajah Pertama", description: "Mulai perjalanan petualangan matematika dengan login.", icon: "🧭" },
  { id: "relasi_master", name: "Ahli Fungsi", description: "Menyelesaikan Level 1 (Hutan Relasi dan Fungsi) dengan gemilang.", icon: "🌳" },
  { id: "sungai_navigator", name: "Navigator Sungai", description: "Menyelesaikan Level 2 (Sungai Grafik Fungsi) tanpa tersesat.", icon: "🌊" },
  { id: "tebing_climber", name: "Pemanjat Tebing", description: "Menaklukkan Level 3 (Tebing Gradien) yang curam.", icon: "🧗" },
  { id: "jembatan_builder", name: "Arsitek Garis", description: "Menyeberangi Level 4 (Jembatan Persamaan Garis) dengan kokoh.", icon: "🌉" },
  { id: "desa_kades", name: "Kepala Statistika", description: "Mengatur data di Level 5 (Desa Statistik) dengan rapi.", icon: "🏡" },
  { id: "gua_explorer", name: "Ekspedisi Gua", description: "Menembus kegelapan Level 6 (Gua Analisis Data) secara logis.", icon: "🔦" },
  { id: "final_boss_slayer", name: "Kesatria Matematika", description: "Mengalahkan Final Boss Naga Math-Gorath dan menyelamatkan dunia angka!", icon: "🐉" },
  { id: "perfect_score", name: "Petualang Sempurna", description: "Mencapai skor maksimal pada salah satu level tantangan.", icon: "👑" },
  { id: "life_saver", name: "Pantang Menyerah", description: "Berhasil bangkit kembali dari keterbatasan energi/nyawa.", icon: "💖" },
];

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 1,
    name: "Level 1: Hutan Relasi & Fungsi",
    environment: "Hutan",
    description: "Petualangan dimulai di hutan lebat. Temukan hubungan antar pepohonan dan makhluk hidup menggunakan konsep relasi dan fungsi.",
    storyIntro: "Kamu memasuki 'Hutan Relasi dan Fungsi'. Daun pepohonan yang rimbun membentuk jaring-jaring panah yang misterius. Untuk membuka jalan rahasia, kamu harus mengelompokkan daerah asal (domain) dan daerah hasil (range) dengan tepat!",
    storyOutro: "Luar biasa! Gapura kayu besar di ujung hutan terbuka karena kamu berhasil membuktikan hubungan fungsional di antara tumbuhan hutan.",
    themeColor: "emerald",
    bgGradient: "from-emerald-950 via-emerald-800 to-teal-980",
    soundAmbience: "rainforest",
    questions: [
      {
        id: "lvl1_q1",
        type: "DRAG_DROP",
        topic: "Relasi dan Fungsi",
        difficulty: "Mudah",
        prompt: "Kelompokkan nilai di bawah menjadi Domain (daerah asal), Kodomain (daerah kawan), atau Range (daerah hasil) sesuai dengan diagram panah yang kamu analisis di dahan pohon beringin!",
        storySegment: "Kamu menemukan ukiran kuno di pohon beringin tua yang mendefinisikan sebuah fungsi $f: A \\rightarrow B$, dengan $A = \\{1, 2, 3\\}$, $B = \\{a, b, c, d\\}$, dan himpunan pasangan berurutannya adalah $\\{(1, a), (2, b), (3, b)\\}$.",
        explanationHint: "Domain adalah seluruh anggota himpunan daerah asal $A$ yaitu {1, 2, 3}. Kodomain adalah seluruh anggota daerah kawan $B$ yaitu {a, b, c, d}. Range adalah hasil yang ditunjuk di $B$ yaitu {a, b}.",
        correctAnswer: "1,2,3=Domain; a,b,c,d=Kodomain; a,b=Range",
        dragItems: [
          { id: "item1", text: "{1, 2, 3}" },
          { id: "item2", text: "{a, b, c, d}" },
          { id: "item3", text: "{a, b}" },
        ],
        dropZones: [
          { id: "zone1", label: "Domain (Daerah Asal)", correctItemIds: ["item1"] },
          { id: "zone2", label: "Kodomain (Daerah Kawan)", correctItemIds: ["item2"] },
          { id: "zone3", label: "Range (Daerah Hasil)", correctItemIds: ["item3"] },
        ],
        visual: {
          type: "diagram_panah",
          arrowDiagram: {
            domain: [
              { id: "1", label: "1" },
              { id: "2", label: "2" },
              { id: "3", label: "3" },
            ],
            kodomain: [
              { id: "a", label: "a" },
              { id: "b", label: "b" },
              { id: "c", label: "c" },
              { id: "d", label: "d" },
            ],
            relations: [
              { from: "1", to: "a" },
              { from: "2", to: "b" },
              { from: "3", to: "b" },
            ],
          },
        },
      },
      {
        id: "lvl1_q2",
        type: "PILIHAN_GANDA",
        topic: "Penyajian Relasi",
        difficulty: "Sedang",
        prompt: "Diberikan dua himpunan hewan hutan: $P = \\{1, 2\\}$ dan $Q = \\{2, 3, 4\\}$. Jika didefinisikan sebuah relasi dari $P$ ke $Q$ yang bermakna **'kurang dari'**, manakah himpunan pasangan berurutan yang paling tepat untuk mendeskripsikan jalan rahasia ini?",
        storySegment: "Kamu melihat kawanan semut berbaris membawa makanan dari koloni P ke koloni Q. Aturan jalannya adalah angka di P harus 'kurang dari' angka di Q.",
        explanationHint: "Mari uji setiap anggota: 1 kurang dari 2, 3, dan 4. Berarti pasangannya (1,2), (1,3), (1,4). Kemudian 2 kurang dari 3 dan 4. Berarti pasangannya (2,3), (2,4). Digabungkan menjadi: {(1,2), (1,3), (1,4), (2,3), (2,4)}.",
        options: [
          "A. {(1,2), (1,3), (1,4), (2,3), (2,4)}",
          "B. {(1,2), (2,3), (2,4)}",
          "C. {(1,3), (1,4), (2,4)}",
          "D. {(2,1), (3,1), (4,1), (3,2), (4,2)}",
        ],
        correctAnswer: "A. {(1,2), (1,3), (1,4), (2,3), (2,4)}",
        visual: {
          type: "pasangan_berurutan",
        },
      },
      {
        id: "lvl1_q3",
        type: "BENAR_SALAH",
        topic: "Definisi Fungsi",
        difficulty: "Sedang",
        prompt: "Apakah himpunan pasangan berurutan berikut merupakan sebuah **Fungsi (Pemetaan)**?\n\n$R = \\{(1, x), (2, y), (3, y), (1, z)\\}$",
        storySegment: "Ada jaring laba-laba raksasa di depan gua kayu. Jaring tersebut memetakan partikel angin R. Jika ini adalah fungsi, kita boleh memotongnya. Jika bukan fungsi, memotongnya akan memicu jebakan angin!",
        explanationHint: "Pada himpunan pasangan berurutan, suatu relasi merupakan fungsi jika setiap anggota domain (elemen pertama) dipasangkan dengan tepat satu anggota kodomain. Di sini, angka 1 dipasangkan dengan x dan juga dengan z (cabang). Jadi, relasi ini bukan fungsi.",
        options: ["Benar (Ini Fungsi)", "Salah (Bukan Fungsi)"],
        correctAnswer: "Salah (Bukan Fungsi)",
      },
    ],
  },
  {
    id: 2,
    name: "Level 2: Sungai Grafik Fungsi",
    environment: "Sungai",
    description: "Arus sungai deras mengalir membentuk alur koordinat linear. Hitung nilai fungsi air dan lintasi jembatan batu.",
    storyIntro: "Kamu tiba di 'Sungai Grafik Fungsi'. Gemercik air yang mengalir tenang rupanya membentuk garisan grafik Kartesius. Untuk menyeberangi sungai ini menggunakan tumpukan batu, kamu harus mencocokkan nilai koordinat yang benar!",
    storyOutro: "Hebat! Kamu melompati jembatan batu dengan lincah seiring nilai fungsi dan titik koordinat yang kamu selesaikan memunculkan batu pijakan baru.",
    themeColor: "sky",
    bgGradient: "from-sky-950 via-sky-850 to-indigo-950",
    soundAmbience: "river",
    questions: [
      {
        id: "lvl2_q1",
        type: "ISIAN_SINGKAT",
        topic: "Nilai Fungsi",
        difficulty: "Mudah",
        prompt: "Diberikan fungsi aliran air $f(x) = 2x - 3$. Hitunglah berapa nilai keluaran fungsi $f(x)$ jika variabel $x$ (kecepatan arus) bernilai $5$!",
        storySegment: "Kamu sedang mengamati alat ukur tekanan air sungai. Rumus tekanannya adalah $f(x) = 2x - 3$. Kamu harus memasukkan nilai tekanan saat kecepatan arusnya $x = 5$.",
        explanationHint: "Substitusikan nilai x = 5 ke dalam rumus f(x) = 2x - 3. Maka, f(5) = 2(5) - 3 = 10 - 3 = 7.",
        correctAnswer: "7",
        acceptedAnswers: ["7", "f(5)=7", "tujuh"],
      },
      {
        id: "lvl2_q2",
        type: "PILIHAN_GANDA",
        topic: "Titik Potong Grafik",
        difficulty: "Sedang",
        prompt: "Tentukan di titik manakah grafik fungsi linear aliran sungai $f(x) = -3x + 6$ memotong sumbu-$Y$ pada sistem koordinat Kartesius!",
        storySegment: "Sebuah dahan kayu tumbang melintang di atas air. Sudut kemiringannya memotong sumbu vertikal peta koordinatmu. Untuk membersihkannya, tebak koordinat potongnya!",
        explanationHint: "Grafik akan memotong sumbu-Y ketika x = 0. Jika disubstitusikan x = 0 ke rumus f(x) = -3(0) + 6, diperoleh f(0) = 6. Maka titik potong sumbu-Y berada pada koordinat (0, 6).",
        options: [
          "A. (0, 6)",
          "B. (6, 0)",
          "C. (0, -3)",
          "D. (-3, 0)",
        ],
        correctAnswer: "A. (0, 6)",
        visual: {
          type: "grafik_kartesius",
          cartesiusGraph: {
            lineEquation: { m: -3, c: 6, label: "y = -3x + 6" },
            points: [{ x: 0, y: 6, label: "Titik Potong Sumbu Y (0,6)" }],
          },
        },
      },
      {
        id: "lvl2_q3",
        type: "KOORDINAT_PUZZLE",
        topic: "Membaca Koordinat Kartesius",
        difficulty: "HOTS",
        prompt: "Klik tepat pada titik Koordinat $(2, 4)$ di peta grid sungai ini untuk menembbak sasaran mengambang yang menahan kunci peta jembatan!",
        storySegment: "Ada gelembung air raksasa berputar-putar di koordinat (2, 4) membawa botol petunjuk berikutnya. Bidik sasaran secara presisi dengan mengeklik titik itu!",
        explanationHint: "Koordinat (2, 4) berarti kamu berjalan 2 satuan ke kanan pada sumbu mendatar (X) dan naik 4 satuan ke atas pada sumbu tegak (Y).",
        correctAnswer: "2,4",
        targetCoordinates: [{ x: 2, y: 4 }],
        gridLimits: { minX: -5, maxX: 5, minY: -5, maxY: 5 },
        visual: {
          type: "grafik_kartesius",
          cartesiusGraph: {
            showGrid: true,
            targetPoint: { x: 2, y: 4 },
          },
        },
      },
    ],
  },
  {
    id: 3,
    name: "Level 3: Tebing Gradien",
    environment: "Tebing",
    description: "Tebing terjal membentang tinggi ke awan. Kamu harus mengukur kemiringan (gradien) tali pemanjat agar dapat mendaki.",
    storyIntro: "Kamu tiba di kaki 'Tebing Gradien'. Dinding batu tinggi menjulang dengan kemiringan ekstrem. Kamu harus menghitung tingkat kecondongan tangga-tangga tali purba agar tidak tergelincir jatuh saat mendaki!",
    storyOutro: "Hebat sekali! Tali pengait telah terpasang pada sudut kemiringan stabil berkat perhitungan gradien yang sangat akurat.",
    themeColor: "amber",
    bgGradient: "from-amber-950 via-amber-900 to-orange-950",
    soundAmbience: "mountain_wind",
    questions: [
      {
        id: "lvl3_q1",
        type: "ISIAN_SINGKAT",
        topic: "Gradien Dua Titik",
        difficulty: "Mudah",
        prompt: "Hitunglah kemiringan (gradien) lintasan tambang yang membentang dari titik batu bawah $A(1, 2)$ menuju titik gantung atas $B(3, 8)$!",
        storySegment: "Sebuah katrol penyelamat berada di atas tebing. Kamu perlu menyetel rem katrol dengan rumus gradien garis hubung kedua titik tersebut.",
        explanationHint: "Gunakan rumus gradien antara dua titik: m = (y2 - y1) / (x2 - x1). Maka m = (8 - 2) / (3 - 1) = 6 / 2 = 3.",
        correctAnswer: "3",
        acceptedAnswers: ["3", "m=3", "tiga"],
      },
      {
        id: "lvl3_q2",
        type: "PILIHAN_GANDA",
        topic: "Gradien Persamaan Garis",
        difficulty: "Sedang",
        prompt: "Berapa gradien ($m$) dari baris dahan tebing yang memiliki pola matematis $3x - 2y = 6$?",
        storySegment: "Kamu melihat reruntuhan pilar batu kuno dengan grafiti angka romawi berupa persamaan linear. Mengetahui gradiennya akan membuat pilar tersebut berputar membuka gua rahasia.",
        explanationHint: "Ubah persamaan 3x - 2y = 6 ke bentuk umum y = mx + c. Pindahkan ruas: -2y = -3x + 6, bagi kedua ruas dengan -2: y = (3/2)x - 3. Jadi, gradien (m) adalah koefisien variabel x yaitu 3/2.",
        options: [
          "A. 3",
          "B. 3/2",
          "C. -3/2",
          "D. -3",
        ],
        correctAnswer: "B. 3/2",
      },
      {
        id: "lvl3_q3",
        type: "PILIHAN_GANDA",
        topic: "Hubungan Dua Garis",
        difficulty: "HOTS",
        prompt: "Tali pembantu pendaki harus dipasang tegak lurus dengan tebing utama yang memiliki persamaan garis bergradien $m_1 = -1/2$. Berapakah nilai gradien $m_2$ yang harus dipunyai oleh tali pembantu tersebut?",
        storySegment: "Keselamatanmu tergantung pada tali pengaman sekunder. Syarat gravitasi menginstruksikan tali pengaman harus tegak lurus (perpendicular) sempurna terhadap talimu saat ini.",
        explanationHint: "Dua garis saling tegak lurus jika hasil kali gradiennya bernilai -1 (m1 * m2 = -1). Dengan m1 = -1/2, maka (-1/2) * m2 = -1, sehingga m2 = 2.",
        options: [
          "A. 1/2",
          "B. -2",
          "C. 2",
          "D. -1/2",
        ],
        correctAnswer: "C. 2",
      },
    ],
  },
  {
    id: 4,
    name: "Level 4: Jembatan Persamaan Garis",
    environment: "Jembatan",
    description: "Jembatan gantung rusak menyeberangi ngarai berapi. Susun persamaan garis yang kuat untuk merekonstruksi jembatan.",
    storyIntro: "Kamu berdiri di depan jurang berapi 'Jembatan Persamaan Garis'. Kayu-kayu jembatan patah berhamburan. Kamu harus menyambung rantai besi dengan menghitung persamaan garis linear yang menghubungkan ujung jurang satu ke ujung jurang lainnya!",
    storyOutro: "Lolos dari maut! Jembatan gantung bermetamorfosis menjadi jembatan baja kokoh berwarna neon biru setelah semua rantai garis lurus terhubung sempurna.",
    themeColor: "red",
    bgGradient: "from-red-950 via-orange-950 to-neutral-900",
    soundAmbience: "lava_fire",
    questions: [
      {
        id: "lvl4_q1",
        type: "PILIHAN_GANDA",
        topic: "Persamaan Garis Gradien & Titik",
        difficulty: "Mudah",
        prompt: "Tentukan persamaan garis lurus yang melewati pasak awal di pilar batu $(0, 3)$ dengan kemiringan jembatan $m = 2$!",
        storySegment: "Kamu harus memproyeksikan tali baja penahan jembatan. Tali dimulai dari elevasi 3 meter di sumbu tegak, dengan kemiringan konstan 2.",
        explanationHint: "Gunakan rumus y - y1 = m(x - x1). Substitusi m = 2, x1 = 0, y1 = 3 menjadi: y - 3 = 2(x - 0) => y = 2x + 3. Ini adalah bentuk umum persamaan garis tersebut.",
        options: [
          "A. y = 2x + 3",
          "B. y = 2x - 3",
          "C. y = 3x + 2",
          "D. y = -2x + 3",
        ],
        correctAnswer: "A. y = 2x + 3",
      },
      {
        id: "lvl4_q2",
        type: "MENJODOHKAN",
        topic: "Persamaan Garis Dua Titik",
        difficulty: "Sedang",
        prompt: "Bantu pasangkan petualangan mencari persamaan garis yang melewati dua titik $G(1, 3)$ dan $H(2, 5)$ dengan langkah-langkah solusinya yang tepat agar paku rivet jembatan terpasang!",
        storySegment: "Pilar gantung rusak membutuhkan 3 pasak pemulihan yang berurutan. Kamu harus menyortir logika penyelesaiannya dari atas ke bawah.",
        explanationHint: "Langkah 1: Hitung gradien m = (5-3)/(2-1) = 2. Langkah 2: Gunakan persamaan y - y1 = m(x - x1) menjadi y - 3 = 2(x - 1). Langkah 3: Sederhanakan menjadi y = 2x + 1.",
        matchingLeft: [
          "Langkah 1 (Hitung Gradien m)",
          "Langkah 2 (Substitusi Titik)",
          "Langkah 3 (Bentuk Akhir Garis)",
        ],
        matchingRight: [
          "y = 2x + 1",
          "m = (5-3)/(2-1) = 2",
          "y - 3 = 2(x - 1)",
        ],
        matchingCorrect: {
          "Langkah 1 (Hitung Gradien m)": "m = (5-3)/(2-1) = 2",
          "Langkah 2 (Substitusi Titik)": "y - 3 = 2(x - 1)",
          "Langkah 3 (Bentuk Akhir Garis)": "y = 2x + 1",
        },
      },
      {
        id: "lvl4_q3",
        type: "PILIHAN_GANDA",
        topic: "Titik Potong Sumbu X",
        difficulty: "Sedang",
        prompt: "Tentukan koordinat titik potong terhadap sumbu-$X$ dari jembatan kabel baja yang mempunyai persamaan $2x + 5y = 10$!",
        storySegment: "Ujung kabel jangkar paling bawah merasuk ke tanah mendatar sumbu-X. Di koordinat manakah kabel itu dinonaktifkan agar tidak menyengat listrik?",
        explanationHint: "Kabel memotong sumbu-X jika nilai y = 0. Masukkan ke persamaan: 2x + 5(0) = 10 => 2x = 10 => x = 5. Jadi, koordinatnya berada pada (5, 0).",
        options: [
          "A. (0, 2)",
          "B. (5, 0)",
          "C. (-5, 0)",
          "D. (2, 0)",
        ],
        correctAnswer: "B. (5, 0)",
      },
    ],
  },
  {
    id: 5,
    name: "Level 5: Desa Statistik",
    environment: "Desa",
    description: "Penduduk desa menderita kelaparan data pertanian. Susun statistik produksi sayuran mereka agar merata.",
    storyIntro: "Kamu tiba di 'Desa Statistik'. Para petani ramah sedang kebingungan menghitung rata-rata (mean), nilai tengah (median), dan kemunculan terbanyak (modus) hasil padi mereka. Bantu mereka menginterpretasi data agar panen melimpah!",
    storyOutro: "Lumbung pangan desa terisi penuh! Kepala desa menganugerahi kamu medali statistik emas atas penyusunan dan interpretasi data yang efisien.",
    themeColor: "indigo",
    bgGradient: "from-indigo-950 via-teal-950 to-emerald-950",
    soundAmbience: "farm_morning",
    questions: [
      {
        id: "lvl5_q1",
        type: "ISIAN_SINGKAT",
        topic: "Mean Data Tunggal",
        difficulty: "Mudah",
        prompt: "Sebuah keranjang berisi berat singkong (dalam kg) sebagai berikut: $6, 7, 8, 5, 9, 8, 7, 6$. Hitunglah nilai rata-rata (mean) dari data berat singkong tersebut!",
        storySegment: "Kepala dusun ingin membagikan bantuan pupuk sama rata berdasarkan bobot singkong rata-rata dari 8 kebun contoh.",
        explanationHint: "Jumlahkan semua nilai: 6 + 7 + 8 + 5 + 9 + 8 + 7 + 6 = 56. Hitung jumlah sampel data (n) = 8. Mean = Jumlah / Banyak data = 56 / 8 = 7.",
        correctAnswer: "7",
        acceptedAnswers: ["7", "7 kg", "tujuh"],
      },
      {
        id: "lvl5_q2",
        type: "PILIHAN_GANDA",
        topic: "Median Tabel Frekuensi",
        difficulty: "Sedang",
        prompt: "Dari data hasil cabai panen di bawah ini, berapakah nilai median (nilai tengah) yang membelah data panen menjadi dua kubu seimbang?\n\n| Nilai Hasil (kg) | Frekuensi (Kebun) |\n|---|---|\n| 5 | 3 |\n| 6 | 4 |\n| 7 | 5 |\n| 8 | 4 |\n| 9 | 2 |",
        storySegment: "Kamu membuka catatan pembukuan lumbung desa. Jumlah seluruh kebun sampel adalah 18 unit.",
        explanationHint: "Total frekuensi N = 18 (genap). Median terletak antara data ke-9 dan data ke-10 setelah diurutkan. Mari cari sebarannya: Nilai 5 (data ke 1-3), Nilai 6 (data ke 4-7, akumulasi = 7), Nilai 7 (data ke 8-12, akumulasi = 12). Karena data ke-9 dan ke-10 berada di kelompok nilai 7, maka median = 7.",
        options: [
          "A. 6",
          "B. 6.5",
          "C. 7",
          "D. 8",
        ],
        correctAnswer: "C. 7",
        visual: {
          type: "freq_table",
          freqTable: {
            headers: ["Nilai Hasil (kg)", "Frekuensi (Kebun)"],
            rows: [[5, 3], [6, 4], [7, 5], [8, 4], [9, 2]],
          },
        },
      },
      {
        id: "lvl5_q3",
        type: "PILIHAN_GANDA",
        topic: "Modus Frekuensi",
        difficulty: "Mudah",
        prompt: "Analisislah diagram frekuensi hasil susu sapi perah di peternakan desa. Susu botol dengan volume berapakah yang menjadi Modus (paling sering diproduksi)?",
        storySegment: "Grafik produksi susu sapi harian menunjukkan puncak tiang tertinggi yang melambangkan kemunculan kembar paling banyak terjadi.",
        explanationHint: "Modus adalah nilai data yang memiliki frekuensi tertinggi atau paling sering muncul. Dari data frekuensi: Nilai 5 frekuensi 3, Nilai 6 frekuensi 4, Nilai 7 frekuensi 5, Nilai 8 frekuensi 4, Nilai 9 frekuensi 2. Nilai 7 memiliki frekuensi tertinggi yaitu 5, sehingga modusnya adalah 7.",
        options: [
          "A. 5 kg",
          "B. 6 kg",
          "C. 7 kg",
          "D. 8 kg",
        ],
        correctAnswer: "C. 7 kg",
      },
    ],
  },
  {
    id: 6,
    name: "Level 6: Gua Analisis Data",
    environment: "Gua",
    description: "Kegelapan gua menuntut kamu mendeteksi pencilan data, kuartil pembagi, dan rentang mineral berharga.",
    storyIntro: "Kamu turun ke dalam 'Gua Analisis Data'. Dinding kristal memancarkan spektrum data rahasia. Kamu harus menganalisis jangkauan kuartil data mineral agar dapat membimbing jalan pulang keluar gua!",
    storyOutro: "Cahaya mentari menyapa! Dengan penguasaan kuartil dan simpangan data, kamu memandu seluruh kelompok keluar dari labirin gua berbatu dengan selamat.",
    themeColor: "purple",
    bgGradient: "from-purple-950 via-neutral-900 to-indigo-950",
    soundAmbience: "cave_echo",
    questions: [
      {
        id: "lvl6_q1",
        type: "ISIAN_SINGKAT",
        topic: "Jangkauan Data (Range)",
        difficulty: "Mudah",
        prompt: "Ditemukan 7 butir kristal ruby dengan ukuran karat: $12, 15, 18, 14, 20, 22, 17$. Carilah jankauan (rentang) ukuran karat kristal terkecil hingga terbesar!",
        storySegment: "Pintu gerbang kristal terkunci sabuk laser. Kunci pembuka kodenya adalah selisih antara kristal termewah dengan kristal terkecil.",
        explanationHint: "Jangkauan data (range) dicari dengan cara menilai nilai maksimum dikurangi nilai minimum. Nilai maks = 22, Nilai min = 12. Range = 22 - 12 = 10.",
        correctAnswer: "10",
        acceptedAnswers: ["10", "10 karat", "sepuluh"],
      },
      {
        id: "lvl6_q2",
        type: "PILIHAN_GANDA",
        topic: "Aplikasi Ukuran Pemusatan",
        difficulty: "Sedang",
        prompt: "Sebuah koperasi gua ingin menyetok helm safety pelindung kepala paling laku. Dari survei ukuran kepala pekerja tambang yang bervariasi, manakah ukuran pemusatan data yang paling mendesak dan tepat dipakai sebagai patokan stok barang?",
        storySegment: "Persediaan logistik gua terbatas. Inventaris toko harus disinkronkan dengan angka ukuran kepala yang paling dominan muncul di populasi.",
        explanationHint: "Untuk memproduksi atau menyetok barang dagangan seperti helm, baju, atau sepatu, ukuran pemusatan yang paling tepat adalah Modus (nilai paling banyak muncul), karena mengincar kelompok pembeli terbesar.",
        options: [
          "A. Mean (Rata-rata)",
          "B. Median (Nilai Tengah)",
          "C. Modus (Paling Sering Muncul)",
          "D. Jangkauan Kuartil",
        ],
        correctAnswer: "C. Modus (Paling Sering Muncul)",
      },
      {
        id: "lvl6_q3",
        type: "PILIHAN_GANDA",
        topic: "Kuartil Data",
        difficulty: "HOTS",
        prompt: "Analisislah diagram kotak garis (boxplot) kandungan emas batuan gua berikut. Manakah angka yang menunjukkan batas Kuartil Atas ($Q_3$) dari persebaran emas tersebut?",
        storySegment: "Peta sensor termografis menggambarkan lima titik sebaran statistik fungsional emas: Min = 5, Q1 = 15, Q2 (Median) = 25, Q3 = 35, Maks = 50.",
        explanationHint: "Kuartil ketiga atau kuartil atas (Q3) adalah titik pembatas 75% data di sebelah kiri dan 25% data di sebelah kanan. Dari data sensor: Q1=15, Q2=25, Q3=35, Maks=50. Maka Kuartil atas adalah 35.",
        options: [
          "A. 15",
          "B. 25",
          "C. 35",
          "D. 50",
        ],
        correctAnswer: "C. 35",
        visual: {
          type: "kuartil_box",
          boxplot: { min: 5, q1: 15, q2: 25, q3: 35, max: 50 },
        },
      },
    ],
  },
  {
    id: 7,
    name: "Final Boss: Candi Pemutus Math-Gorath",
    environment: "Candi",
    description: "Pertarungan epik melawan Naga Penjaga Kuil Matematika. Kerahkan seluruh ilmu numerasi matematika SMP-mu!",
    storyIntro: "Kamu menginjakkan kaki di pelataran 'Candi Pemutus'. Dari kawah asap membubung, naga legendaris Math-Gorath bangkit menantangmu! Dia memegang segel suci peradaban angka. Kalahkan naga ini dengan memecahkan 5 teka-teki integratif HOTS terakhir!",
    storyOutro: "KEDAMAIAN TELAH KEMBALI! Naga Math-Gorath menunduk hormat kepada kecerdasanmu dan menganugerahkan Mahkota Emas 'Pradnya Paramita' - bukti tamat petualangan luhur Lintas Alam Matematika SMP!",
    themeColor: "violet",
    bgGradient: "from-slate-950 via-violet-950 to-purple-950",
    soundAmbience: "epic_boss",
    questions: [
      {
        id: "boss_q1",
        type: "PILIHAN_GANDA",
        topic: "Relasi dan Fungsi (HOTS)",
        difficulty: "HOTS",
        prompt: "Fungsi kekuatan api naga dirumuskan dengan $f(x) = ax + b$. Jika naga membakar tumpukan kayu dengan level $f(2) = 7$ dan level $f(-1) = 1$, tentukan rumus fungsi kekuatan api tersebut yang sebenarnya agar kamu bisa meredamnya!",
        storySegment: "Math-Gorath menyemburkan api linear. Kamu harus meretas jalinan persamaan koefisien matematika penentu suhu api.",
        explanationHint: "Gunakan eliminasi/substitusi:\n1) f(2) = 2a + b = 7\n2) f(-1) = -a + b = 1\nKurangi (1) dengan (2): 3a = 6 => a = 2.\nSubstitusikan a = 2 ke persamaan (2): -2 + b = 1 => b = 3.\nJadi, rumus fungsinya adalah f(x) = 2x + 3.",
        options: [
          "A. f(x) = 2x + 3",
          "B. f(x) = 3x + 1",
          "C. f(x) = 2x - 3",
          "D. f(x) = -2x + 5",
        ],
        correctAnswer: "A. f(x) = 2x + 3",
      },
      {
        id: "boss_q2",
        type: "PILIHAN_GANDA",
        topic: "Grafik Fungsi Linear (Numerasi)",
        difficulty: "HOTS",
        prompt: "Debit air penyembuh kawah candi meningkat stabil secara linear. Pada menit ke-1 tinggi air adalah 4 meter, sedangkan pada menit ke-4 tinggi air mencapai 10 meter. Berapakah perkiraan tinggi air penyembuh pada menit ke-10 yang harus diisi untuk memadamkan lava?",
        storySegment: "Math-Gorath bersiap melempar lava. Kamu harus mengisi bendungan air suci penyembembuh tepat waktu pada volume menit ke-10.",
        explanationHint: "Misalkan tinggi air y pada menit x mengikuti persamaan linear y = mx + c. \nCari gradien m = (y2-y1)/(x2-x1) = (10-4)/(4-1) = 6/3 = 2 meter/menit.\nUntuk mencari c, gunakan (1,4): 4 = 2(1) + c => c = 2. \nPersamaan tinggi air: y = 2x + 2. Pada menit x = 10, tinggi air y = 2(10) + 2 = 22 meter.",
        options: [
          "A. 18 meter",
          "B. 20 meter",
          "C. 22 meter",
          "D. 24 meter",
        ],
        correctAnswer: "C. 22 meter",
      },
      {
        id: "boss_q3",
        type: "PILIHAN_GANDA",
        topic: "Garis Tegak Lurus (HOTS)",
        difficulty: "HOTS",
        prompt: "Sebuah perisai petir ajaib melindungi jantung candi. Sudut energi perisai ini terletak pada garis yang melalui titik $(3, -2)$ dan tegak lurus dengan gerak petarung Naga yang bergaris $2x - y = 4$. Carilah persamaan perisai pelindung tersebut!",
        storySegment: "Math-Gorath menyerang dengan berkas petir maut. Aktifkan perisai pelindung dengan meluruskan frekuensi sejajar tegak lurus pada sumbu energi.",
        explanationHint: "Ubah 2x - y = 4 menjadi y = 2x - 4. Garis ini bergradien m1 = 2. Garis perisai yang tegak lurus harus memiliki gradien m2 = -1/2 (karena m1*m2 = -1). \nPersamaan garis perisai bergradien m2 = -1/2 melalui (3, -2):\ny - y1 = m2(x - x1) => y - (-2) = -1/2 (x - 3) => y + 2 = -1/2 x + 3/2.\nKalikan dengan 2: 2y + 4 = -x + 3 => x + 2y + 1 = 0.",
        options: [
          "A. x + 2y + 1 = 0",
          "B. 2x - y - 8 = 0",
          "C. x - 2y - 7 = 0",
          "D. 2x + y - 4 = 0",
        ],
        correctAnswer: "A. x + 2y + 1 = 0",
      },
      {
        id: "boss_q4",
        type: "PILIHAN_GANDA",
        topic: "Statistika Terapan (Numerasi)",
        difficulty: "Sedang",
        prompt: "Sembilan kesatria mula-mula memiliki rata-rata (mean) skor pertahanan 70. Datang satu ksatria pelindung senior yang bergabung sehingga nilai rata-rata gabungan mereka bersepuluh naik menjadi 72. Berapakah skor pertahanan ksatria senior tersebut?",
        storySegment: "Kamu memanggil ksatria pelindung dari langit untuk menyatukan barisan pertahanan magis.",
        explanationHint: "Total nilai awal 9 ksatria = 9 * 70 = 630.\nTotal nilai akhir 10 ksatria setelah senior gabung = 10 * 72 = 720.\nSkor ksatria senior = Total akhir - Total awal = 720 - 630 = 90.",
        options: [
          "A. 80",
          "B. 85",
          "C. 90",
          "D. 92",
        ],
        correctAnswer: "C. 90",
      },
      {
        id: "boss_q5",
        type: "BENAR_SALAH",
        topic: "Analisis Data (HOTS)",
        difficulty: "HOTS",
        prompt: "Math-Gorath mengklaim bahwa jika ia menambahkan nilai ekstrim sangat tinggi (outlier) ke dalam daftar statistik, maka nilai **Median** selalu akan bergeser jauh lebih besar dibandingkan nilai **Mean**.\n\nApakah pernyataan taktis naga tersebut secara matematika **Benar** atau **Salah**?",
        storySegment: "Pertanyaan psikologis terakhir dari sang naga. Jika kamu setuju dengan klaim kelirunya, naga akan memakan energimu. Buktikan ketajaman analisis datamu!",
        explanationHint: "Klaim naga salah. Nilai Mean (rata-rata) sangat rentan dipengaruhi oleh nilai ekstrim (pencilan) dan akan bergeser jauh. Sedangkan nilai Median (nilai tengah) bersifat kokoh (robos) terhadap pencilan karena hanya mengandalkan urutan posisi tengah. Sehingga nilai Mean-lah yang bergeser jauh lebih besar daripada Median.",
        options: [
          "Benar (Klaim Naga Benar)",
          "Salah (Klaim Naga Salah)"
        ],
        correctAnswer: "Salah (Klaim Naga Salah)",
      }
    ],
  },
];
